import { OrderStatus } from "@/types";

export const ORDER_STATUS_RULES = {
  CUSTOMER: ["PENDING", "CANCELLED"],
  ADMIN: ["PENDING", "AGREED", "SHIPPED", "DELIVERED", "CANCELLED"],
  OPERATOR: ["SHIPPED"],
  DISPATCHER: ["PENDING", "AGREED", "CANCELLED"],
  COURIER: ["DELIVERED"],
};

export const ORDER_STATUS_CAN_VISIBLE = {
  CUSTOMER: ["PENDING", "AGREED", "SHIPPED", "DELIVERED", "CANCELLED"],
  ADMIN: ["PENDING", "AGREED", "SHIPPED", "DELIVERED", "CANCELLED"],
  OPERATOR: ["AGREED", "SHIPPED"],
  DISPATCHER: ["PENDING", "AGREED", "SHIPPED", "DELIVERED", "CANCELLED"],
  COURIER: ["AGREED", "SHIPPED", "DELIVERED"],
};

export const ROLE_DEFAULT_STATUS: Record<string, OrderStatus> = {
  CUSTOMER: "PENDING",
  ADMIN: "PENDING",
  OPERATOR: "AGREED",
  DISPATCHER: "PENDING",
  COURIER: "SHIPPED",
};
